### ISSUE TITLE
Does this plugin seeds images?

### ISSUE THREAD

**Issue by kevinNgws** [VirtusLab/strapi-molecules#30]
Hi, does this plugin seed images as well? Especially for collection type with array of components. For example: 

`user: { companies: [{name: A, image: A.png}, ...]}`

**Comment by mstrag** [comment]
Hi Kevin,
Currently, plugin offers very basic usage, and allow to seed contentTypes using json files we just sync it to database. if You are using URL of file it will be saved to DB, however image itself won't be copied. 

I'm planning to develop a little bit this plugin and update readme, to allow seeding more complicated structures, however I recommend it only for development purposes, in production I recommend to use Knex builtin seeds/migrations - which also have possibility to rollback.

For more info You can find me on official Strapi Slack channel.
