### ISSUE TITLE
strapi-plugin-preview buttons not showing using extension instructions

### ISSUE THREAD

**Issue by derrickmehaffy** [VirtusLab/strapi-molecules#35]
Hello VirtusLab team from the Strapi team o/

A member of our community alerted me to your `strapi-plugin-preview` plugin and I was giving it a test run :wink: 

Three things of note:

- The link to the document on NPM is broken: https://www.npmjs.com/package/strapi-plugin-preview as it linkes to: https://www.npmjs.com/package/README-EXTENSIONS.md which doesn't exist.
- The second is those instructions state: `Strapi-plugin-versioning needs extension files to work properly.` I assume this is just a small typo as nowhere is it specified in that package is required for the preview plugin.
- And finally I could not for the life of me to get the extensions to actually apply if the package is installed via NPM, I'll be doing some testing manually throwing the plugin in the `plugins` folder but figured I would leave you with a test project I created:

[testPreview.tar.gz](https://github.com/VirtusLab/strapi-molecules/files/5726661/testPreview.tar.gz)

```
User login: test@test.com
Pass: Test1234!
```

Side note, congrats on the various packages. By all means, if you have not please do feel free to submit a PR to our [awesome-strapi](https://github.com/strapi/awesome-strapi) repo.

---

Also, have you tested any of your plugins with our latest release that includes the relational fields in the list view?
https://github.com/strapi/strapi/releases/tag/v3.4.0

**Comment by cyp3rius** [comment]
Hi @derrickmehaffy :)

Great to hear from you! Thanks for the feedback and what I can say it's my fault that Molecules hasn't been yet submitted to the awesome-strapi like other plugins (comments, navigation) as I've asked my teammates to lift a bit the docs to prepare it for community :)

Regarding the 3.4.0 we would like to give a try to this version early January as current scope in commercial project where we've got version 3.3.4 is going to be closed and passed to test, then hope to get some slots for community stuff ;)

**Comment by derrickmehaffy** [comment]
Absolutely, I believe @vcoisne will probably contact you guys to setup a call at some point in January (we were just talking about it internally).

Talking with a few users on the community slack, it appears there are some issues in some of your other packages. I've put them on my list to test as well (though I might not get to it this week) but I'll try and provide you some feedback. :smiley: 

Looking forward to seeing what else you guys work on, quite excited to see some plugins from a commercial org! Keep up the great work!

**Comment by cyp3rius** [comment]
Happy to catch :)

Feel free to involve us to the discussions and share observations you've got. Advices from the Strapi core will help us to make it better

**Comment by AlexStansfield** [comment]
I just spent some time trying to get the versioning plugin installed but hit a snag with these extension files. They don't seem to be compatible with Strapi 3.4.x. 

I found this issue which gives hope support might come soon, but I was wondering if there was an easier way of applying the content-manager changes rather than copy and paste from the repo. 

Perhaps diff could be supplied that can be applied?

**Comment by ngjoni** [comment]
+1

**Comment by SalahAdDin** [comment]
I was thinking on use this but it seems to be not compatible with the last **Strapi** version.

**Comment by cyp3rius** [comment]
We have had on a pipeline aligning this to the most recent Strapi version as part of daily basis project we are doing. Results soon.

**Comment by AdamDemirel** [comment]
Hi there, i'm also running into this same issue following the project setup to a T with strapi@3.3.3 (see attached videos)

pt1: https://streamable.com/xthi11
pt2: https://streamable.com/hcc9oz

**Comment by SalahAdDin** [comment]
Is this problem present with the last **Strapi** version?

**Comment by Kronos66** [comment]
Yes, this is present with all content types where we have draft and publish flow (I tested this on 3.3.3 and 3.5.3 Strapi versions). In a new version which is in progress, I will add config for this :). New version will support 3.5.3 strapi version.
