### ISSUE TITLE
Audit Log missing configuration instructions

### ISSUE THREAD

**Issue by AlexStansfield** [VirtusLab/strapi-molecules#38]
I was wondering if there were some configuration instructions for the Audit log. 

I'm running it in Strapi 3.4.6. From the Navigation plugin I managed to figure out this config:

```
{
    "audit-log": {
      "enabled": true,
      "exclude": [],
      "map": []
    }
  }
```

However nothing happens when I change any content records. 

I couldn't quite figure out if I was meant to put things in `map` and if so, what it was.

**Comment by Kronos66** [comment]
Hi @AlexStansfield,

Great to hear from you! Thanks for the feedback and I will add instruction for this package soon.
