### ISSUE TITLE
Invalid schema configuration: `CurrentTimestamp` audit-log

### ISSUE THREAD

**Issue by shtelzerartem** [VirtusLab/strapi-molecules#41]
Hey! I'm experiencing this error, when trying to start working with audit-log plugin.

**Setup:**
Strapi: 3.5.1
DB: Mongo

![image](https://user-images.githubusercontent.com/20266461/109143104-54ec2b80-7768-11eb-922e-4d8eea73e263.png)

Isn't it better just to use ```timestamps: true``` in ```audit_logs.settings.json``` provided by Strapi?

**Comment by Kronos66** [comment]
Hi @shtelzerartem,

sorry so the late response.
I checked that problem and it will be fixed in the new version with migrating to new strapi version :)

**Comment by shtelzerartem** [comment]
> Hi @shtelzerartem,
> 
> sorry so the late response.
> I checked that problem and it will be fixed in the new version with migrating to new strapi version :)

Cook, good to hear that, would be happy to test it, when you will finish
